[application]
name = "PPOCGen"
default_platform = "web"
hot_reload = true

[web.app]
title = "PPOC Gen"
[web.resource]
style = ["assets/tailwind.css"]
script = []
[web.resource.dev]
script = []
[web.wasm_opt]
level = "z"
[web.watcher]
index_on_404 = true
watch_path = ["src", "assets"]

#------------------------------------------
# Bundler
#------------------------------------------
[bundle]
identifier = "io.github.ppocgen"
publisher = "MarckFp"
copyright = ""
category = "Utility"
short_description = "An amazing dioxus application."
long_description = """
An amazing dioxus application.
"""
icon = [
    "assets/icons/128x128.png",
    "assets/icons/128x128@2x.png",
    "assets/icons/32x32.png",
    "assets/icons/android-chrome-192x192.png",
    "assets/icons/android-chrome-512x512.png",
    "assets/icons/apple-touch-icon.png",
    "assets/icons/favicon-16x16.png",
    "assets/icons/favicon-32x32.png",
    "assets/icons/favicon.ico",
    "assets/icons/icon.ico",
    "assets/icons/icon.png"
]

#------------------------------------------
# Windows
#------------------------------------------
[bundle.windows]
icon_path = "icons/icon.ico"
allow_downgrades = false
tsp = false
webview_install_mode = {DownloadBootstrapper = {silent = true}}
silent = true
[bundle.windows.nsis]
installer_icon = "icons/icon.ico"
install_mode = "Both"
display_language_selector = false

#------------------------------------------
# MacOS
#------------------------------------------
[bundle.macos]
hardened_runtime = true
[bundle.macos.files]